version: '3'

services:
  db-mysql:
    image: ${DB_PROVIDER}:${DB_PROVIDER_VERSION}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./${CONTAINER_NAME}-db:/var/lib/mysql
