version: '3'

services:
  db-mysql:
    image: mysql:${MYSQL_IMAGE_VERSION}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./db-${DB_NAME}:/var/lib/mysql
    networks:
      - todos-app-network
  app:
    container_name: nuxt-todo-app
    image: dragon-azul-todo-app
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db-mysql
    networks:
      - todos-app-network
    links:
      - db-mysql

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - todos-app-network

networks:
  todos-app-network:
    driver: bridge
