version: '3'

services:
  db-mysql:
    image: ${DB_PROVIDER}:${DB_PROVIDER_VERSION}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./${CONTAINER_NAME}-db:/var/lib/mysql
    networks:
      - todos-app-network
  app:
    container_name: nuxt-todo-app
    image: dragon-azul-todo-app
    build: .
    ports:
      - ${APP_PORT}:3000
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db-mysql
    networks:
      - todos-app-network
    links:
      - db-mysql
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - todos-app-network

networks:
  todos-app-network:
