version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '8080:80'
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
  db-mysql:
    image: ${DB_PROVIDER}:${DB_PROVIDER_VERSION}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./${CONTAINER_NAME}-db:/var/lib/mysql
    networks:
      - todos-app-network
  app:
    container_name: nuxt-todo-app
    image: dragon-azul-todo-app
    build: .
    ports:
      - ${APP_PORT}:3000
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db-mysql
    networks:
      - todos-app-network
    links:
      - db-mysql
  

networks:
  todos-app-network:

volumes:
  conf:
  vhost:
  html:
  certs:
  acme: